#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
PYTHONPATH="${HERE}"/usr/lib/python2.7:$PYTHONPATH LD_LIBRARY_PATH="${HERE}/usr/lib/:${LD_LIBRARY_PATH}" PATH="${HERE}/:${PATH}" exec "${HERE}"/AppImageAssistant "$@"
